CREATE TABLE `rescued_animals` (
	`id` text PRIMARY KEY NOT NULL,
	`happen_date` text,
	`happen_place` text,
	`kind_cd` text,
	`color_cd` text,
	`age` text,
	`weight` text,
	`notice_no` text,
	`notice_sdt` text,
	`notice_edt` text,
	`image_url` text,
	`process_state` text,
	`sex_cd` text,
	`neuter_yn` text,
	`care_nm` text,
	`care_tel` text,
	`care_addr` text,
	`charge_nm` text,
	`org_nm` text,
	`notice_comment` text,
	`last_synced_at` text NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL
);
